#define PLAYER_SPEED_NORMALIZED			20.0f
#define	PLAYER_SPEED_NON_NORMALIZED		3.0f
#define PLAYER_SPEED_PER_SECOND			0.48f	

#define SPEED_PFLAK		90.0f
#define SPEED_SFLAK		100.0f//TEMP, originale è 60.0f
#define SPEED_SFLAK_V0	175.0f
#define SPEED_GRANADE	80.0f
#define SPEED_ROCKET	80.0f
#define SPEED_SSHOCK	60.0f
#define SPEED_PLINK		45.0f
#define ACCEL_PLINK		5.5f
#define SPEED_GES		80.0f
#define SPEED_PGES_V0   200.0f
#define SPEED_SGES_V0   140.0f


#define SHOCK_CORE_MIN_TRACKING_DIST	200.0f

#define SHOCK_COMBO_AUTOBLAST_RANGE_MIN	140.0f
#define SHOCK_COMBO_AUTOBLAST_RANGE_MAX	400.0f

#define MAX_XHAIR_SIZE					350

#define DEFAULT_UNLOCK_STR  20
#define DEFAULT_AIM_SPEED	40
#define DEFAULT_XHAIR_SIZE  50

#define FAKE_INPUT 1000

#define WEAPON_RANGE_INFINITE -1
